//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnitTestSteamPowered.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UnitTestSteamPowered.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to === 2. Move to the Action Game Page ===.
        /// </summary>
        internal static string StrGoActionPage {
            get {
                return ResourceManager.GetString("StrGoActionPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to === 3. Move to the Download Game Page ===.
        /// </summary>
        internal static string StrGoDownloadGame {
            get {
                return ResourceManager.GetString("StrGoDownloadGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to === 4. Move to the Download Steam Page ===.
        /// </summary>
        internal static string StrGoDownloadSteam {
            get {
                return ResourceManager.GetString("StrGoDownloadSteam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to === Initializing test === .
        /// </summary>
        internal static string StrInitTest {
            get {
                return ResourceManager.GetString("StrInitTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to === 1. Open Main Page===.
        /// </summary>
        internal static string StrOpenMainPage {
            get {
                return ResourceManager.GetString("StrOpenMainPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to === Test resaults ===.
        /// </summary>
        internal static string StrTestResaults {
            get {
                return ResourceManager.GetString("StrTestResaults", resourceCulture);
            }
        }
    }
}
