//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PagesSteamPowered.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PagesSteamPowered.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        internal static string ConfigEnLang {
            get {
                return ResourceManager.GetString("ConfigEnLang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Russian.
        /// </summary>
        internal static string ConfigRuLang {
            get {
                return ResourceManager.GetString("ConfigRuLang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filling the Age Gate fields.
        /// </summary>
        internal static string StrAgeGateFilds {
            get {
                return ResourceManager.GetString("StrAgeGateFilds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking dowloading steam file.
        /// </summary>
        internal static string StrCheckingDowloadingFile {
            get {
                return ResourceManager.GetString("StrCheckingDowloadingFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking game params for equal.
        /// </summary>
        internal static string StrCheckingGameParams {
            get {
                return ResourceManager.GetString("StrCheckingGameParams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirming the Age Gate.
        /// </summary>
        internal static string StrConfirmAgeGate {
            get {
                return ResourceManager.GetString("StrConfirmAgeGate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find the game with max price.
        /// </summary>
        internal static string StrFindMaxPriceGame {
            get {
                return ResourceManager.GetString("StrFindMaxPriceGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://store.steampowered.com/.
        /// </summary>
        internal static string UrlPage {
            get {
                return ResourceManager.GetString("UrlPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to language.
        /// </summary>
        internal static string ValueEngLang {
            get {
                return ResourceManager.GetString("ValueEngLang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to язык.
        /// </summary>
        internal static string ValueRuLang {
            get {
                return ResourceManager.GetString("ValueRuLang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //*[@id=&quot;genre_flyout&quot;]/div/a[contains(text(),&apos;.
        /// </summary>
        internal static string XPathActionBtn {
            get {
                return ResourceManager.GetString("XPathActionBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //*[@id=&quot;agecheck_form&quot;]/select[@name=&quot;ageDay&quot;].
        /// </summary>
        internal static string XPathAgeDay {
            get {
                return ResourceManager.GetString("XPathAgeDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //*[@id=&quot;app_agegate&quot;].
        /// </summary>
        internal static string XPathAgeGateApp {
            get {
                return ResourceManager.GetString("XPathAgeGateApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //div[@id=&quot;agegate_box&quot;] .
        /// </summary>
        internal static string XPathAgeGateBox {
            get {
                return ResourceManager.GetString("XPathAgeGateBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //*[@id=&quot;agecheck_form&quot;]/select[@name=&quot;ageMonth&quot;].
        /// </summary>
        internal static string XPathAgeMonth {
            get {
                return ResourceManager.GetString("XPathAgeMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //*[@id=&quot;agecheck_form&quot;]/select[@name=&quot;ageYear&quot;].
        /// </summary>
        internal static string XPathAgeYear {
            get {
                return ResourceManager.GetString("XPathAgeYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //*[@id=&quot;app_agegate&quot;]//span[contains(text(),&apos;.
        /// </summary>
        internal static string XPathBtnContinueOnAgeGateApp {
            get {
                return ResourceManager.GetString("XPathBtnContinueOnAgeGateApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //*[@id=&quot;DiscountsRows&quot;]/a[contains(text(),&apos;%&apos;)].
        /// </summary>
        internal static string XPathDiscounts {
            get {
                return ResourceManager.GetString("XPathDiscounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //div[@class=&quot;discount_pct&quot;].
        /// </summary>
        internal static string XPathDiscountSelectedGame {
            get {
                return ResourceManager.GetString("XPathDiscountSelectedGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //*[@id=&quot;tab_select_Discounts&quot;]/div.
        /// </summary>
        internal static string XPathDiscountsTab {
            get {
                return ResourceManager.GetString("XPathDiscountsTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //*[@id=&quot;global_action_menu&quot;]/div/a.
        /// </summary>
        internal static string XPathDownloadLink {
            get {
                return ResourceManager.GetString("XPathDownloadLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //*[@id=&quot;about_install_steam_link&quot;].
        /// </summary>
        internal static string XPathDownloadSteamBtn {
            get {
                return ResourceManager.GetString("XPathDownloadSteamBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //*[@id=&apos;language_dropdown&apos;]/div/a[contains(text(),&apos;English&apos;)].
        /// </summary>
        internal static string XPathEngLocal {
            get {
                return ResourceManager.GetString("XPathEngLocal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //*[@id=&quot;genre_tab&quot;]/span/a[contains(text(),&apos;.
        /// </summary>
        internal static string XPathGameDropDown {
            get {
                return ResourceManager.GetString("XPathGameDropDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //div[@id=&quot;genre_tab&quot;]//span/span.
        /// </summary>
        internal static string XPathGameDropDownSpanSpan {
            get {
                return ResourceManager.GetString("XPathGameDropDownSpanSpan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //*[@id=&quot;language_pulldown&quot;].
        /// </summary>
        internal static string XPathLocalLangDropDown {
            get {
                return ResourceManager.GetString("XPathLocalLangDropDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //title.
        /// </summary>
        internal static string XPathPageTitle {
            get {
                return ResourceManager.GetString("XPathPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //*[@class=&quot;discount_final_price&quot;].
        /// </summary>
        internal static string XPathPriceSelectedGame {
            get {
                return ResourceManager.GetString("XPathPriceSelectedGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //*[@id=&apos;language_dropdown&apos;]/div/a[contains(text(),&apos;Russian&apos;)].
        /// </summary>
        internal static string XPathRuLocal {
            get {
                return ResourceManager.GetString("XPathRuLocal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //*[@id=&quot;agecheck_form&quot;]/a/span.
        /// </summary>
        internal static string XPathSubmitAgeButton {
            get {
                return ResourceManager.GetString("XPathSubmitAgeButton", resourceCulture);
            }
        }
    }
}
